### ISSUE TITLE
unable to force 1024x768 mode

### ISSUE THREAD

**Issue by dbrown2k** [verser-git/probe_screen_v2#7]
I have laptop with 1280x800 screen and the probe tab is cut off in AXIS GUI, how do i force probe_screen to use the 1024x768 resolution icons?

**Comment by dbrown2k** [comment]
I solved this by replacing in the ini file the following
`EMBED_TAB_COMMAND=halcmd loadusr -Wn gladevcp gladevcp -c gladevcp -x {XID} -u python/probe_screen.py -H probe_icons/probe_screen.hal probe_icons/probe_screen.glade`

with

`EMBED_TAB_COMMAND=halcmd loadusr -Wn gladevcp gladevcp -c gladevcp -x {XID} -u python/probe_screen.py -H probe_icons_1024x768/probe_screen.hal probe_icons_1024x768/probe_screen.glade`

**Comment by verser-git** [comment]
Thank you.
